name: buf
on:
  push:
    paths:
      - 'proto/**'
  workflow_dispatch:
permissions:
  contents: read
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: bufbuild/buf-setup-action@v1.50.0
      - uses: bufbuild/buf-lint-action@v1.1.1
        with:
          buf_token: ${{ secrets.BUF_TOKEN }}
#  breaking:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4.2.2
#      - uses: bufbuild/buf-setup-action@v1.50.0
#      - uses: bufbuild/buf-breaking-action@v1.1.4
#        with:
#          against: 'https://github.com/bufbuild/connect-demo.git#branch=main'
#          input: proto
  push:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs:
      - lint
#      - breaking
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: bufbuild/buf-setup-action@v1.50.0
      - uses: bufbuild/buf-push-action@v1.1.4
        with:
          input: 'proto'
          buf_token: ${{ secrets.BUF_TOKEN }}
